### PR TITLE
Short-circuit the backoff if Min backoff is greater than Max

### PR DESCRIPTION
**Pull request by dividinglimits**

### CODE REVIEW

**Comment by jpillora** [comment]
Interesting. What's your use-case for when `Min` is greater than `Max`?

**Comment by dividinglimits** [comment]
API based generation of backoff strategy. I think it would be nice to add debug/warning log, but that doesn't currently exist so didn't want to ammend the implementation to introduce side effects here

**Comment by jpillora** [comment]
Alrighty, sounds reasonable

**Comment by jpillora** [comment]
Thanks :)

**Pull request merged**
